SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS user_info;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS appointment;

SET FOREIGN_KEY_CHECKS = 1;